services:
  service-registry:
    build:
      context: ../clean-pro-solutions-service-registry
      dockerfile: Dockerfile
    container_name: bff-registry
    ports:
      - "8770:8761"
    networks:
      - bff-net

  bff-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bff-service
    ports:
      - "8080:8080"
    environment:
      EUREKA_SERVER_URL: http://service-registry:8761/eureka
    depends_on:
      - service-registry
    networks:
      - bff-net

networks:
  bff-net:
    driver: bridge
